### PR TITLE
Add Dockerfile to run locally

### PR DESCRIPTION
**Pull request by boaz0**
Run project-koku website locally using Docker

### CODE REVIEW

**Comment by cybette** [comment]
@adberglund can you please take a look? thanks.

btw I don't have much access in this repo, I wasn't able to add reviewers, much less add a review :)

**Comment by boaz0** [comment]
@cybette me too. I don't have permissions. @adberglund can you do that?

**Comment by adberglund** [comment]
@boaz0  and @cybette Can you try now? I updated the repo access so hopefully should have rights now!

**Comment by boaz0** [comment]
@adberglund still cannot add/remove reviewers or labels

**Comment by boaz0** [comment]
Now it's working. Thanks @adberglund

**Review by cybette — APPROVED** [review]

**Comment by boaz0** [comment]
Thank you all @cybette & @adberglund

**Pull request merged**
